### ISSUE TITLE
Bug with the license

### ISSUE THREAD

**Issue by devironl** [carrotsearch/elasticsearch-lingo3g#1]
Hello

I have followed all the steps you have indicated and I have put my valid license file (license.xml) in the ES home directory

However I got the following error while starting Elasticsearch

`java.lang.NoClassDefFoundError: com/carrotsearch/lingo3g/impl/OptionalLicenseLocationSupplier`

Do you know how to fix this ?

Thanks and best regards

Louis

**Comment by dweiss** [comment]
Seems like you're missing Lingo3G JAR (lingo3g-2.0.0-beta1.jar) - unless you're building from sources you need to put this in the plugin's folder manually:
```
Alternatively, you can also fetch and modify plugin binaries from Maven Central.

Once the ZIP distribution of the plugin is downloaded, you will have to add Lingo3G JAR to the archive, then proceed with elasticsearch-plugin installation above.
```

**Comment by devironl** [comment]
Thank you for the quick reply

I already did it. After installation, the Lingo3G jar (lingo3g-1.15.0.jar) is well in the plugin folder (/elasticsearch/plugins/elasticsearch-lingo3g). Should it also be in the carrot2 plugin folder ?

I am using the version 1.15.0 of Lingo3G. Is it compatible ?

Thanks !

**Comment by dweiss** [comment]
This plugin works only with Lingo3G 2.x (beta). For Lingo3G 1.x (stable), you'll need to revert back to a previous version of Carrot2-elasticsearch plugin and then install just the JARs (and required libraries), as explained here:

https://get.carrotsearch.com/lingo3g/manual/#section.es

Binaries of ES-compatible Carrot2 plugins are here --
https://repo1.maven.org/maven2/org/carrot2/elasticsearch-carrot2/

but you may have to recompile from sources... it depends which ES version you want to run against. 

All this said - it may be easier to use the Lingo3G DCS and just fetch documents from ES, then pass them for clustering to the clustering service...
